export type ProfessionalFormValue = {
  id: string;
  name: string;
  nickname: string | null;
  color: string;
  phone: string | null;
  specialty: string | null;
  commissionPct: number;
  active: boolean;
  workStart: string;
  workEnd: string;
  imageUrl: string | null;
  birthDate: string | null;
  document: string | null;
  rg: string | null;
  notes: string | null;
  zip: string | null;
  address: string | null;
  addressNumber: string | null;
  complement: string | null;
  district: string | null;
  city: string | null;
  state: string | null;
  onlineBooking: boolean;
  generateAgenda: boolean;
  receivesCommission: boolean;
  isStockist: boolean;
  salonPartner: boolean;
  sortOrder: number;
  user: { id: string; email: string; role: string; name: string } | null;
  serviceIds: string[];
};
