export type ClientFormValue = {
  id: string;
  name: string;
  nickname: string | null;
  phone: string;
  landline: string | null;
  email: string | null;
  birthDate: string | null;
  notes: string | null;
  tags: string;
  instagram: string | null;
  facebook: string | null;
  cnpj: string | null;
  cpf: string | null;
  rg: string | null;
  imageUrl: string | null;
  referredById: string | null;
  zip: string | null;
  address: string | null;
  addressNumber: string | null;
  complement: string | null;
  district: string | null;
  city: string | null;
  state: string | null;
  defaultDiscountPct: number;
  discountTarget: string;
  active: boolean;
  notifications: boolean;
  blockAccess: boolean;
  lastService: string | null;
  hasDebt: boolean;
};
